In [376]:
import numpy as np      #To Prform Numerical Operation
import matplotlib.pyplot as plt   #plot something 
import pandas as pd     #To Play With Dataset
import math

In [377]:
from google.colab import drive #to import the google drive data

In [378]:
drive.mount('/content/drive')   # to mount the drive data into the colab cloud and enter the activation code

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [379]:
cd /content/drive/"My Drive/ML nishit sir/Ass3- KNN" 

/content/drive/My Drive/ML nishit sir/Ass3- KNN


In [380]:
dataset = pd.read_csv("HR_comma_sep.csv")
print(dataset)

       satisfaction_level  last_evaluation  ...  Department  salary
0                    0.38             0.53  ...       sales     low
1                    0.80             0.86  ...       sales  medium
2                    0.11             0.88  ...       sales  medium
3                    0.72             0.87  ...       sales     low
4                    0.37             0.52  ...       sales     low
...                   ...              ...  ...         ...     ...
14994                0.40             0.57  ...     support     low
14995                0.37             0.48  ...     support     low
14996                0.37             0.53  ...     support     low
14997                0.11             0.96  ...     support     low
14998                0.37             0.52  ...     support     low

[14999 rows x 10 columns]


In [381]:
dataset.head()

satisfaction_level  last_evaluation  ...  Department  salary
0                0.38             0.53  ...       sales     low
1                0.80             0.86  ...       sales  medium
2                0.11             0.88  ...       sales  medium
3                0.72             0.87  ...       sales     low
4                0.37             0.52  ...       sales     low

[5 rows x 10 columns]

In [382]:
dataset.tail()

satisfaction_level  last_evaluation  ...  Department  salary
14994                0.40             0.57  ...     support     low
14995                0.37             0.48  ...     support     low
14996                0.37             0.53  ...     support     low
14997                0.11             0.96  ...     support     low
14998                0.37             0.52  ...     support     low

[5 rows x 10 columns]

In [383]:
dataset.shape

(14999, 10)

In [384]:
training = dataset.values[:,0:6]

In [385]:
training

array([[0.38, 0.53, 2, 157, 3, 0],
       [0.8, 0.86, 5, 262, 6, 0],
       [0.11, 0.88, 7, 272, 4, 0],
       ...,
       [0.37, 0.53, 2, 143, 3, 0],
       [0.11, 0.96, 6, 280, 4, 0],
       [0.37, 0.52, 2, 158, 3, 0]], dtype=object)

In [386]:
trainingclass = dataset.values[:,-4]
trainingclass

array([1, 1, 1, ..., 1, 1, 1], dtype=object)

In [387]:
trainingclass.shape

(14999,)

In [388]:
# Calculate Distance between two points using Euclidean distance
def euclidean_distance(d1,d2):
    distance=0.0
    for i in range(len(d1)):
        distance+=(d1[i]-d2[i])**2
    return math.sqrt(distance)

In [389]:
#To convert categorical value to numerical value
unique_list=[0,1]
'''for x in trainingclass:
    if x not in unique_list:
        unique_list.append(x)

print(unique_list)'''

for i in range(len(trainingclass)):
    for k in range(len(unique_list)):
        if(trainingclass[i] == unique_list[k]):
            trainingclass[i]=k

print(trainingclass)

[1 1 1 ... 1 1 1]


In [390]:
# Calculate distance from any one point to other all points
distance=[]
for i in range(len(training)):
    distance.append([euclidean_distance(training[i],training[7442]),trainingclass[i]])
print(distance)

[[40.11596814237443, 1], [145.01102371888834, 1], [155.0381969064398, 1], [106.01051693110453, 1], [42.11056518262371, 1], [36.128311612916534, 1], [130.02604239151478, 1], [142.00766352559992, 1], [107.01086533618911, 1], [25.184322504288257, 1], [18.254415904103862, 1], [188.0180427512211, 1], [117.00532039185227, 1], [31.149067401769834, 1], [20.231643531853756, 1], [26.178101535443705, 1], [43.106997111837885, 1], [138.00844358226783, 1], [43.095452196258485, 1], [145.00770358846458, 1], [165.02060477407056, 1], [30.15452370706591, 1], [187.01856271504172, 1], [22.208604188467135, 1], [41.11289457092507, 1], [125.00896167875325, 1], [122.00492490059571, 1], [18.25551149653167, 1], [11.412751640161105, 1], [15.306397355354393, 1], [177.018949550606, 1], [17.269371731478827, 1], [28.164987129413, 1], [23.19969827390003, 1], [129.00852103640287, 1], [138.02505642092672, 1], [20.230714273104645, 1], [9.498236678457744, 1], [189.01812505683154, 1], [35.13206654895211, 1], [152.007250156

In [391]:
len(distance)

14999

In [392]:
distance.sort()
distance

[[0.0, 0],
 [1.2996153277027784, 0],
 [1.4728543716199507, 0],
 [1.4728543716199507, 0],
 [1.5495160534825059, 0],
 [1.7632073048850496, 0],
 [1.9117531221368518, 0],
 [2.099761891262912, 0],
 [2.099761891262912, 0],
 [2.247487486060823, 0],
 [2.247487486060823, 0],
 [2.2872253933532654, 0],
 [2.332766597840427, 0],
 [2.3386534587236305, 0],
 [2.4517952606202664, 0],
 [2.468886388637598, 0],
 [2.5238858928247927, 0],
 [2.527231687044146, 0],
 [2.5273899580397168, 0],
 [2.5626548733686323, 0],
 [2.5626548733686323, 0],
 [2.5681510858981795, 0],
 [2.5681510858981795, 0],
 [2.5683652388241045, 0],
 [2.6468471810816734, 0],
 [2.685609800399157, 0],
 [2.7074157419945686, 0],
 [2.7370787347096903, 0],
 [3.0421702779430344, 0],
 [3.0558959406367228, 0],
 [3.0566975643658303, 0],
 [3.07001628660175, 0],
 [3.135745525389457, 0],
 [3.135745525389457, 0],
 [3.185121661726597, 0],
 [3.1977648443874043, 0],
 [3.198906063015918, 0],
 [3.2098909638802375, 0],
 [3.212117681530364, 0],
 [3.218524506664

In [393]:
nearest_neighbour = 5

In [394]:
identify=[0 for i in range(len(unique_list))]
for i in range(nearest_neighbour):
    identify[distance[i][1]]=identify[distance[i][1]]+1
print(identify)



[5, 0]


In [395]:
ab=unique_list[identify.index(max(identify))]
if(ab==0):
  print("The Predicted Class is not Left the company")
else:
  print("The Predicted Class is Left the company")

The Predicted Class is not Left the company
